name: Build and Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: docker/cache-action@v2
      with:
        path: |
          /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/arnaqueoupas:latest
        cache-from: type=gha,scope=buildx
        cache-to: type=gha,mode=max,scope=buildx

    - name: Deploy to GitHub Packages
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag ghcr.io/${{ github.repository_owner }}/arnaqueoupas:latest ghcr.io/${{ github.repository_owner }}/arnaqueoupas:latest
        docker push ghcr.io/${{ github.repository_owner }}/arnaqueoupas:latest
