name: Build and Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Building Docker image..."
        docker build . -t ghcr.io/${{ github.repository_owner }}/email-checker:latest
        echo "Running Docker container..."
        docker run -e EMAIL_USER="${{ secrets.EMAIL_USER }}" \
                   -e EMAIL_PASS="${{ secrets.EMAIL_PASS }}" \
                   -e SMTP_SERVER="${{ secrets.SMTP_SERVER }}" \
                   -e IMAP_SERVER="${{ secrets.IMAP_SERVER }}" \
                   -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
                   ghcr.io/${{ github.repository_owner }}/email-checker:latest
